version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'quiz'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'quiz'
      MYSQL_ROOT_PASSWORD: 'quiz'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: