server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #statusPageUrlPath: ${server.servletPath}/info
    #healthCheckUrlPath: ${server.servletPath}/health
    #instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
